# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          lastgleaming
paginate:       5
baseurl:        ""
url:            "https://lastgleam.github.io"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         lastgleam
  url:          https://lastgleam.github.io
  email:        lastgleam@gmail.com

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/lastgleam/lastgleam.github.io

# Gems
plugins:
  - jekyll-paginate
